---
title: "Hotel Cancellation - Decision Trees"
author: "Caitlin Howansky & Wei Li"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: '3'
  html_notebook:
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
---

#__Get Data Ready__
```{r message = FALSE, echo = FALSE, error = FALSE}
# Clear environment of variables and functions
#rm(list = ls(all = TRUE)) 
# Clear environmet of packages
#if(is.null(sessionInfo()$otherPkgs) == FALSE)lapply(paste("package:", names(sessionInfo()$otherPkgs), #sep=""), detach, character.only = TRUE, unload = TRUE)
```

```{r message = FALSE, echo = FALSE, error = FALSE}
library(tidyverse) 
library(dplyr) # joins
#library(janitor) # pretty cross-tabs
library(kableExtra) # pretty html tables
#library(formattable)
#library(gridExtra)
#library(scales)
#library(pastecs)
#library(GGally)
library(lubridate)
#library(directlabels)
#library(Metrics)
library(tree)
library(ISLR)
library(MASS)
library(rpart)

```

```{r message = FALSE, echo = FALSE, error = FALSE}
# disable scientific notation in R
options(scipen=999)
```

```{r message = FALSE, echo = FALSE, error = FALSE}
# load the data files
hot1 <- read_csv('BOOKINGS_ATLCP.csv')
hot2 <- read_csv('BOOKINGS_NYCHA.csv')
```

```{r}
# change date fields to date
hot1$stay_dt <- as.Date(hot1$stay_dt, "%m/%d/%Y")
hot1$booking_dt <- as.Date(hot1$booking_dt, "%m/%d/%Y")
hot2$stay_dt <- as.Date(hot2$stay_dt, "%m/%d/%Y")
hot2$booking_dt <- as.Date(hot2$booking_dt, "%m/%d/%Y")
#create field for non-numerical dow
hot1$day_of_week <- as.factor(hot1$dow)
hot2$day_of_week <- as.factor(hot2$dow)
```

```{r}
# filter OTB=0, truncate the data by dp, add price, otb_cxl_rate, day_type, month, regrouping tags to the dataset
# Reserve last 3 weeks data as Validation Data and the prior are Training Data
hot1 <- hot1 %>% 
  filter(OTB!=0, days_prior<33) %>% 
  mutate(price=OTB_rev/OTB, OTB_cxl_rate = OTB_to_be_cxl/OTB,
         day_type = as.factor(case_when(day_of_week == '7' ~ 'weekend',
                              day_of_week == '1' ~ 'weekend', 
                              TRUE ~'weekday')),
         month = as.factor(month(stay_dt)),
         prod_group_perc = as.factor(case_when(product_type == 'OPAQUE' ~ 'OP/FENC',
                                         product_type == 'FENCED' ~ 'OP/FENC',
                                         product_type == 'CORPORATE' ~ 'CORP/BUS',
                                         product_type == 'BUSINESS TRAVEL AGENCIES' ~ 'CORP/BUS',
                                         product_type == 'GROUP' ~ 'GROUP',
                                         product_type == 'MEMBERSHIP MARKETING' ~ 'MEM/OTHER',
                                         product_type == 'OTHER' ~ 'MEM/OTHER',
                                         product_type == 'UNFENCED' ~ 'GOV/UNFENC',
                                         product_type == 'GOVERNMENT' ~ 'GOV/UNFENC')),
         prod_group_behav = as.factor(case_when(product_type == 'OPAQUE' ~ 'OP/FENC/OTH',
                                         product_type == 'FENCED' ~ 'OP/FENC/OTH',
                                         product_type == 'CORPORATE' ~ 'CORPORATE',
                                         product_type == 'BUSINESS TRAVEL AGENCIES' ~ 'GOV/BUS/MEM',
                                         product_type == 'GROUP' ~ 'GROUP',
                                         product_type == 'MEMBERSHIP MARKETING' ~ 'GOV/BUS/MEM',
                                         product_type == 'OTHER' ~ 'OP/FENC/OTH',
                                         product_type == 'UNFENCED' ~ 'UNFENCED',
                                         product_type == 'GOVERNMENT' ~ 'GOV/BUS/MEM')),
         prod_group_cxl_rate = as.factor(case_when(product_type == 'OPAQUE' ~ 'GOV/UNFEN/OP',
                                         product_type == 'FENCED' ~ 'CORP/FEN/MEM',
                                         product_type == 'CORPORATE' ~ 'CORP/FEN/MEM',
                                         product_type == 'BUSINESS TRAVEL AGENCIES' ~ 'OTH/BTA',
                                         product_type == 'GROUP' ~ 'GROUP',
                                         product_type == 'MEMBERSHIP MARKETING' ~ 'CORP/FEN/MEM',
                                         product_type == 'OTHER' ~ 'OTH/BTA',
                                         product_type == 'UNFENCED' ~ 'GOV/UNFEN/OP',
                                         product_type == 'GOVERNMENT' ~ 'GOV/UNFEN/OP')),
         day_type_cxl_rate = as.factor(case_when(day_of_week=="1"~"SUN", 
                                                 day_of_week=="6"~"FRI/SAT",
                                                 day_of_week=="7"~"FRI/SAT",
                                                 TRUE ~ "MON/TUE/WED/THU")))
hot2 <- hot2 %>% 
  filter(OTB!=0, days_prior<32) %>% 
  mutate(price=OTB_rev/OTB, OTB_cxl_rate = OTB_to_be_cxl/OTB,
         day_type = as.factor(case_when(day_of_week == '7' ~ 'weekend',
                              day_of_week == '1' ~ 'weekend', 
                              TRUE ~'weekday')),
         month = as.factor(month(stay_dt)),
         prod_group_perc = as.factor(case_when(product_type == 'OPAQUE' ~ 'OP/FENC/OTH',
                                         product_type == 'FENCED' ~ 'OP/FENC/OTH',
                                         product_type == 'CORPORATE' ~ 'CORP/GROUP/TACT',
                                         product_type == 'BUSINESS TRAVEL AGENCIES' ~ 'UNF/WHOLE/MEM/BUS',
                                         product_type == 'GROUP' ~ 'CORP/GROUP/TACT',
                                         product_type == 'TACTICAL MARKETING' ~ 'CORP/GROUP/TACT',
                                         product_type == 'MEMBERSHIP MARKETING' ~ 'UNF/WHOLE/MEM/BUS',
                                         product_type == 'OTHER' ~ 'OP/FENC/OTH',
                                         product_type == 'UNFENCED' ~ 'UNF/WHOLE/MEM/BUS',
                                         product_type == 'GOVERNMENT' ~ 'GOVERNMENT',
                                         product_type == 'WHOLESALE' ~ 'UNF/WHOLE/MEM/BUS')),
         prod_group_behav = as.factor(case_when(product_type == 'OPAQUE' ~ 'OTH/OPA/FEN',
                                         product_type == 'FENCED' ~ 'OTH/OPA/FEN',
                                         product_type == 'CORPORATE' ~ 'CORP/MEMB/WHOLE',
                                         product_type == 'BUSINESS TRAVEL AGENCIES' ~ 'BTA/UNFEN/CORP/MM',
                                         product_type == 'GROUP' ~ 'GROUP',
                                         product_type == 'TACTICAL MARKETING' ~ 'TACT/WHOLE',
                                         product_type == 'MEMBERSHIP MARKETING' ~ 'BTA/UNFEN/CORP/MM',
                                         product_type == 'OTHER' ~ 'OTH/OPA/FEN',
                                         product_type == 'UNFENCED' ~ 'BTA/UNFEN/CORP/MM',
                                         product_type == 'GOVERNMENT' ~ 'GOVERNMENT',
                                         product_type == 'WHOLESALE' ~ 'TACT/WHOLE')),
         day_type_cxl_rate = as.factor(case_when(day_of_week=="1"~"SUN", 
                                                 day_of_week=="6"~"FRI/SAT",
                                                 day_of_week=="7"~"FRI/SAT",
                                                 TRUE ~ "MON/TUE/WED/THU")))
h1_train <- hot1[hot1$stay_dt <= (max(hot1$stay_dt) - 21),]
h2_train <- hot2[hot2$stay_dt <= (max(hot2$stay_dt) - 21),]
h1_test <- hot1[hot1$stay_dt > (max(hot1$stay_dt) - 21),]
h2_test <- hot2[hot2$stay_dt > (max(hot2$stay_dt) - 21),]
# For MASE, use the average survival (= average survival rate of all training data * OTB) as the naive forecast.
avg_svv_rt <- sum(h1_train$OTB_to_survive)/sum(h1_train$OTB)
```

```{r}
# Function to get MAE, MAPE, MASE
eval <- function(test){
  test$fcst_svv <- test$OTB - test$OTB * test$predict_cxl_rate
  tst_mae <- test %>% 
    filter(days_prior!=0) %>% 
    mutate(dp_range = case_when(days_prior >=1 & days_prior<=7 ~ '1_7',
                                  days_prior >=8 & days_prior<=14 ~ '8_14',
                                  days_prior >=15 & days_prior<=21 ~ '15_21',
                                  days_prior >=22 & days_prior<=28 ~ '22_28',
                                  days_prior >=29 ~ '29_32')) %>% 
    group_by(dp_range) %>% 
    summarise(meanAE = mae(OTB_to_survive, fcst_svv))
  tst_mape <- test %>%  
    filter(OTB_to_survive!=0, days_prior!=0) %>% 
    mutate(dp_range = case_when(days_prior >=1 & days_prior<=7 ~ '1_7',
                                  days_prior >=8 & days_prior<=14 ~ '8_14',
                                  days_prior >=15 & days_prior<=21 ~ '15_21',
                                  days_prior >=22 & days_prior<=28 ~ '22_28',
                                  days_prior >=29 ~ '29_32')) %>% 
    group_by(dp_range) %>% 
    summarise(meanAPE = mape(OTB_to_survive, fcst_svv))
  tst_mase <- test %>%  
    filter(days_prior!=0) %>% 
    mutate(dp_range = case_when(days_prior >=1 & days_prior<=7 ~ '1_7',
                                  days_prior >=8 & days_prior<=14 ~ '8_14',
                                  days_prior >=15 & days_prior<=21 ~ '15_21',
                                  days_prior >=22 & days_prior<=28 ~ '22_28',
                                  days_prior >=29 ~ '29_32'),
         abs_diff_1=abs(OTB_to_survive-fcst_svv),
         abs_diff_2=abs(OTB_to_survive-avg_svv_rt*OTB)) %>% 
    group_by(dp_range) %>% 
    summarise(meanASE = sum(abs_diff_1)/sum(abs_diff_2))
  left_join(left_join(tst_mae,tst_mape, by=c("dp_range")), tst_mase, by=c("dp_range"))
}
```

#__Decision Tree Models__
##__Hotel 1__

```{r}
h1_train_1 <- h1_train[,-which(names(h1_train) %in% c('OTB_to_be_cxl', 'OTB_to_survive', 'OTB_rev_to_be_cxl', 'OTB_rev_to_survive', 'daily_gross_rev', 'daily_cxl_rev', 'daily_net_rev', 'cummulative_gross_rev', 'cummulative_cxl_rev', 'OTB_rev', 'month'))]
```


```{r}
first_tree <-  tree(OTB_cxl_rate ~., data = h1_train_1)
summary(first_tree)
plot(first_tree)
text(first_tree, pretty = 0)
first_tree
h1_test$predict_cxl_rate <-  predict(first_tree, h1_test)
dt_best_1 <- eval(h1_test)
h1_train$predict_cxl_rate <-  predict(first_tree, h1_train)
eval(h1_train)


```

- only prod group perc was the only grouping used


```{r}
set.seed(18)
first_tree_cv = cv.tree(first_tree)
plot(first_tree_cv$size, sqrt(first_tree_cv$dev / nrow(h1_train)), type = "b",
     xlab = "Tree Size", ylab = "CV-RMSE")
```
- 10 through 12 has best RMSE so prune to 10 for interpretability


```{r}
pruned_tree_1 <- prune.tree(first_tree, best=10)
plot(pruned_tree_1 )
text(first_tree, pretty = 0)
h1_test$predict_cxl_rate <-  predict(pruned_tree_1, h1_test)
eval(h1_test)
```

```{r}
pruned_tree_2 <- prune.tree(first_tree, best=12)
plot(pruned_tree_1 )
text(first_tree, pretty = 0)
h1_test$predict_cxl_rate <-  predict(pruned_tree_2, h1_test)
eval(h1_test)
h1_train$predict_cxl_rate <-  predict(pruned_tree_2, h1_train)
eval(h1_train)
```

- best = 12 still has best error numbers




##__Hotel 2__

```{r}
h2_train_1 <- h2_train[,-which(names(h1_train) %in% c('OTB_to_be_cxl', 'OTB_to_survive', 'OTB_rev_to_be_cxl', 'OTB_rev_to_survive', 'daily_gross_rev', 'daily_cxl_rev', 'daily_net_rev', 'cummulative_gross_rev', 'cummulative_cxl_rev', 'OTB_rev', 'month'))]
```


```{r}
first_tree_2 = tree(OTB_cxl_rate ~., data = h2_train_1)
summary(first_tree_2)
plot(first_tree_2)
text(first_tree_2, pretty = 0)
first_tree_2
h2_test$predict_cxl_rate <-  predict(first_tree_2, h2_test)
dt_best_2 <- eval(h2_test)
#h2_test$predict_cxl_rate <-  predict(first_tree_2, h2_train)
#eval(h2_train)
```


```{r}
set.seed(18)
first_tree_cv = cv.tree(first_tree)
plot(first_tree_cv$size, sqrt(first_tree_cv$dev / nrow(h1_train)), type = "b",
     xlab = "Tree Size", ylab = "CV-RMSE")
```


```{r}
save.image("dt_env.Rdata")
```

